version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PRIMARY_UN: ${MONGO_PRIMARY_UN}
      MONGO_PRIMARY_PW: ${MONGO_PRIMARY_PW}
    volumes:
      - '$PWD/db/docker-mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - ${MONGO_PORT}:27017
